controller_manager:
  ros__parameters:
    update_rate: 100

    joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    joint_group_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - front_left_hip_x
        - front_left_hip_y
        - front_left_knee
        - front_right_hip_x
        - front_right_hip_y
        - front_right_knee
        - rear_left_hip_x
        - rear_left_hip_y
        - rear_left_knee
        - rear_right_hip_x
        - rear_right_hip_y
        - rear_right_knee

      gains:
        front_left_hip_x:  {p: 600.0, i: 0.9, d: 20.0}
        front_left_hip_y:  {p: 600.0, i: 0.9, d: 20.0}
        front_left_knee:   {p: 600.0, i: 0.9, d: 20.0}
        front_right_hip_x: {p: 600.0, i: 0.9, d: 20.0}
        front_right_hip_y: {p: 600.0, i: 0.9, d: 20.0}
        front_right_knee:  {p: 600.0, i: 0.9, d: 20.0}
        rear_left_hip_x:   {p: 600.0, i: 0.9, d: 20.0}
        rear_left_hip_y:   {p: 600.0, i: 0.9, d: 20.0}
        rear_left_knee:    {p: 600.0, i: 0.9, d: 20.0}
        rear_right_hip_x:  {p: 600.0, i: 0.9, d: 20.0}
        rear_right_hip_y:  {p: 600.0, i: 0.9, d: 20.0}
        rear_right_knee:   {p: 600.0, i: 0.9, d: 20.0}

      state_publish_rate: 50
      action_monitor_rate: 10
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.05
      stop_trajectory_duration: 0.5
